server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: "mongodb+srv://smitkarwade31:karwade31@cluster0.cqvic.mongodb.net/learn_db?retryWrites=true&w=majority"

jwt:
  secret: "thisIsAVeryLongSecretKeyForJWTSigningThatMustBeAtLeast256BitsLongToWorkWithHS256Algorithm"
  access-token-exp-min: 60
  issuer: learnverse-api